let users = {
  KGZA53: {
    email: "damian.marley@gmail.com",
    first_name: "Damian",
    last_name: "Marley",
    id: "0",
    city: "Miami",
    state: "FL",
    country: "USA",
    zip_code: "33145",
    service_history: [
      "Traded a Subaru for a Ferrari",
      "Performed Engine Replacement",
    ],
  },
  AFWG53: {
    email: "timcook@microsoft.com",
    first_name: "Timothy",
    last_name: "Calvert",
    id: "1",
    city: "Palo Alto",
    state: "CA",
    country: "USA",
    zip_code: "94304",
    service_history: [
      "Traded a Corolla for a Porsche",
      "Buy a Lamborginy bugati",
    ],
  },
  GOLGGS: {
    email: "percyjackson@microsoft.com",
    first_name: "Percy",
    last_name: "Jackson",
    id: "2",
    city: "New York",
    state: "New York",
    country: "USA",
    zip_code: "10204",
  },
  AM74043: {
    email: "thomas@gmail.com",
    first_name: "Thomas",
    last_name: "Dubon",
    id: "3",
    city: "Kentucky",
    state: "FC",
    country: "USA",
    zip_code: "12345",
    service_history: ["Sold a Mercedes Benz Class E-340"],
  },
  BKTP665: {
    email: "gera@fiu.edu",
    first_name: "Gera",
    last_name: "George",
    id: "4",
    city: "Miami",
    state: "Florida",
    country: "USA",
    zip_code: "13445",
    service_history: ["Traded a Subaru for a Ferrari "],
  },
  DZVG49: {
    email: "mike@facebook.com",
    first_name: "Mike",
    last_name: "Rockefeler",
    id: "5",
    city: "Los Angeles",
    state: "California",
    country: "USA",
    zip_code: "22667",
    service_history: ["Performed Engine Replacement"],
  },
  EAB0318: {
    email: "rick@morty.com",
    first_name: "Rick",
    last_name: "Sanchez",
    id: "6",
    city: "Orlando",
    state: "Florida",
    country: "USA",
    zip_code: "225547",
    service_history: [],
  },
  ELY035: {
    email: "andres@twiter.com",
    first_name: "Andres",
    last_name: "Melendez",
    id: "7",
    city: "Whisconsing",
    state: "Florida",
    country: "USA",
    zip_code: "22557",
    service_history: ["Traded a Corolla for a Porsche"],
  },
  FRICK50: {
    email: "frank@zukerberg.com",
    first_name: "Frank",
    last_name: "Zukerberg",
    id: "8",
    city: "Los Angeles",
    state: "California",
    country: "USA",
    zip_code: "22627",
    servce_history: [
      "Buy a Ferrary",
      "Sell a bughaty",
      "Trade mercedes for black tesla",
    ],
  },
  HERBOX: {
    email: "julian@fiu.edu",
    first_name: "Julian",
    last_name: "Euceda",
    id: "8",
    city: "New York",
    state: "New York",
    country: "USA",
    zip_code: "226668",
    service_history: [
      "Requested a Refund for his Corolla",
      "Buy a Lamborginy bugati",
    ],
  },
  MG57323: {
    email: "jrodrigo@gmail.edu",
    first_name: "Rodrigo",
    last_name: "Howel",
    id: "9",
    city: "Miami",
    state: "Florida",
    country: "USA",
    zip_code: "89568",
    service_history: [
      "Traded a Subaru for a Mercedez",
      "Buy a Hummer",
      " Sell a bugati",
    ],
  },
};

let advisors = {
  "bill@autonation.com": {
    firstName: "Bill",
    lastName: "Nye",
    photoLink: "#CF4D6F",
    password: "ABC124",
  },
  "douglasadams@autonation.com": {
    firstName: "Douglas",
    lastName: "Adams",
    photoLink: "#CC7E85",
    password: "marco_1234",
  },
  "shawnmendez@autonation.com": {
    firstName: "Douglas",
    lastName: "Adams",
    photoLink: "#A36D90",
    password: "dogslovecats",
  },
};

let parkedUsers = ["AFWG53"];

module.exports = {
  users,
  advisors,
  parkedUsers,
};
